### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by Kilvoctu** [ashen-sensored/sd_webui_stealth_pnginfo#1]
Hello, sorry for the bother. The stealth pnginfo script is fantastic and works as expected. 👍
  
However, it doesn't seem like it's able to be called through the Web UI API; that is, images sent through the API with this script active don't have the stealth png info. I develop a Discord bot which relies on this information.   
Would you be able to add this functionality?  
If it's too much work, then is it okay if I use the code in your `add_stealth_pnginfo` function? I won't need additional help implementing it, and I'll give you credit for the code (and your script will still be needed to read the PNG info in Web UI).  

Thanks very much again for creating this. 👍👍

**Comment by d3x-at** [comment]
If it's no bother, i will add myself into this with a similar question.

I too, am working on a project using your stealth_pnginfo code (the reading portion - see my sd-parsers repo).
If this usage is not to your liking, feel free to tell, and i will remove the offending module.

Also, thank you very much for creating this!

**Comment by ashen-sensored** [comment]
> Hello, sorry for the bother. The stealth pnginfo script is fantastic and works as expected. +1
> 
> However, it doesn't seem like it's able to be called through the Web UI API; that is, images sent through the API with this script active don't have the stealth png info. I develop a Discord bot which relies on this information. Would you be able to add this functionality? If it's too much work, then is it okay if I use the code in your `add_stealth_pnginfo` function? I won't need additional help implementing it, and I'll give you credit for the code (and your script will still be needed to read the PNG info in Web UI).
> 
> Thanks very much again for creating this. +1+1

Oh sorry I didn't see your issue until now.
Yeah, no problem at all. Feel free to submit PR for the api part if you feel like sharing it.

**Comment by ashen-sensored** [comment]
> If it's no bother, i will add myself into this with a similar question.
> 
> I too, am working on a project using your stealth_pnginfo code (the reading portion - see my sd-parsers repo). If this usage is not to your liking, feel free to tell, and i will remove the offending module.
> 
> Also, thank you very much for creating this!

No problem with that, good luck with your project

**Comment by Kilvoctu** [comment]
> Oh sorry I didn't see your issue until now. Yeah, no problem at all. Feel free to submit PR for the api part if you feel like sharing it.

Thanks for your reply 👍 I don't know actually how to do the API part, lol.  
I'll have my app write the stealth pnginfo data, then I'll direct everyone to this repo for the script so their Web UI can interpret the data.

You can close this issue if you'd like.
